"""Layer 1 of 3 — published biological fact. Nothing here is CLIPPR's to choose.

Every literal traces to Farley et al. (2025) or its supplementary tables, or to the NCBI
genetic code. Nothing is copied from any third-party implementation. `scaffold.json` is
generated by `tools/derive_scaffold.py`, which assembles the deposited modules per the
published recipe; re-run that script rather than editing values by hand.

The three layers exist so a future contributor can tell what GRASP *requires* from what
CLIPPR *chose*:

    biology.py         published fact          <- you are here
    assembly_spec.py   assembly mechanics
    policy.py          this project's choices

If you are tempted to add a threshold, a default or a compatibility preference to this
file, it belongs in `policy.py`.
"""
from __future__ import annotations

import json
from pathlib import Path

_DATA = json.loads((Path(__file__).with_name("scaffold.json")).read_text(encoding="utf-8"))

#: PPR code pair -> recognised RNA base.
#: Farley et al. 2025 Fig 1B: Thr/Asn->A, Asn/Asn->C, Thr/Asp->G, Asn/Asp->U.
#: Codes are written (fifth, last); DNA alphabet, so U is stored as T.
CODE_TO_BASE: dict[str, str] = dict(_DATA["code_to_base"])
BASE_TO_CODE: dict[str, str] = {v: k for k, v in CODE_TO_BASE.items()}

#: N-terminal solvating helix, ending in the first VVS of repeat 1.
#:
#: Provenance note. Assembling the deposited modules per Supplementary Tables S1/S2
#: (see tools/derive_scaffold.py) yields "MGNSEEPRKSFDERPERGVVS". The expressed
#: construct carries two further residues, "QG", contributed by the assembly context
#: rather than by any module insert - the module inserts begin at the AATG fusion site
#: and so do not include them. The discrepancy was located by differential comparison
#: by differential comparison against the corpus, and is confined to
#: the N-terminus: it lies outside every PPR repeat and every ARELF motif, so it does
#: not affect specificity, cut placement or overhang selection.
N_TERMINAL: str = "MQGGNSEEPRKSFDERPERGVVS"

#: One PPR repeat. `fifth` and `last` are the two specificity-determining residues.
REPEAT_TEMPLATE: str = "W{fifth}AMISGYAQNGRIDEARELFDKMPER{last}VVS"

#: The invariant motif recurring once per repeat.
ARELF_MOTIF: str = "ARELF"

#: Supported architectures: name -> number of PPR motifs (== target length in nt).
ARCHITECTURES: dict[str, int] = {k: int(v) for k, v in _DATA["architectures"].items()}

#: NCBI genetic code tables. Nuclear is 1; chloroplast/plastid is 11.
#: CLIPPR spans both: the PPR coding sequence is nuclear, the target 5'UTR is chloroplast.
GENETIC_CODE_NUCLEAR: int = 1
GENETIC_CODE_PLASTID: int = 11


def _synonymous_codons() -> dict[str, tuple[str, ...]]:
    """Amino acid -> its codons, from the NCBI standard table via Biopython.

    Tables 1 and 11 share an identical codon->amino-acid map; they differ only in which
    codons may initiate translation. Synonymous substitution is therefore the same in
    the nucleus and the plastid, and one table serves both.
    """
    from Bio.Data import CodonTable

    table = CodonTable.unambiguous_dna_by_id[GENETIC_CODE_NUCLEAR]
    out: dict[str, list[str]] = {}
    for codon, aa in table.forward_table.items():
        out.setdefault(aa, []).append(codon)
    return {aa: tuple(sorted(c)) for aa, c in out.items()}


#: Amino acid -> synonymous codons. Drives overhang variation at Golden Gate cuts.
SYNONYMOUS_CODONS: dict[str, tuple[str, ...]] = _synonymous_codons()

PROVENANCE: str = _DATA["provenance"]
