"""Generate the handover's State table from measured artefacts, so a stale figure cannot ship.

Five figures in this project have now been wrong while every test was green: the tests badge
read 283 against a real 949 and later 927 against a measured 974, the State table read 927
against that same 974, its notebook row read 22 cells against 30, and the release check read
**10 of 10** against a real **8 of 10**. Each was written once by hand, by someone who had just
measured it, and never recomputed afterwards.

Writing them more carefully is not a fix -- that was already the intention every time. So the
measured rows are no longer written by hand. This reads `work/release/release_check.json` and
the notebooks, renders those rows, and by default **verifies** that the handover matches,
exiting non-zero when it does not. That framing is the only one this project has found to work:
a rule that says "reject if X" gets followed, and a rule that says "remember to update X" does
not.

**Only measured rows are generated.** A row that is a judgement -- whether the default
behaviour changed, which commits matter and why -- stays hand-written outside the markers,
because generating a judgement would mean inventing one.

**The input must bind to this tree.** `release_check.json` carries a digest over `src/`,
`tests/` and `release_check.py` -- the three things that can make a measured figure wrong. If
the tree computes a different one, this refuses rather than rendering numbers for a tree that no
longer exists, which is exactly the failure it exists to prevent.

It binds on those and **not** on the commit, although the record carries one. A handover or docs
commit moves HEAD without changing a single measured number, and a gate that fires on every
commit is a gate someone switches off. Nothing volatile reaches the rendered block either: the
record is rewritten by every release-check run, so a timestamp in the output would fail the gate
immediately after each run and make a green release check unreachable.

    python validation/state_table.py            # verify; non-zero if the handover is stale
    python validation/state_table.py --write    # rewrite the block from measured values
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HANDOVER = ROOT / "HANDOVER_TO_CODEX.md"
RECORD = ROOT / "work" / "release" / "release_check.json"
NOTEBOOKS = (("Designer", "CLIPPR_designer.ipynb"), ("Inventory", "CLIPPR_inventory.ipynb"))

BEGIN = "<!-- STATE:BEGIN generated by validation/state_table.py -- do not edit by hand -->"
END = "<!-- STATE:END -->"


class Stale(Exception):
    """The record does not describe this tree, so nothing can be rendered from it."""


def inputs_fingerprint() -> str:
    """Digest of everything that decides the measured rows: package source and the suite.

    Not HEAD. A handover or docs commit moves HEAD without changing a single measured number,
    and a gate that fires on every commit is a gate someone switches off. What can make these
    figures wrong is `src/`, `tests/` and `release_check.py` itself, so those are what bind.
    """
    h = hashlib.sha256()
    # Sorted on the posix relative path, not on Path, whose ordering is case-folded on
    # Windows and case-sensitive on POSIX -- a second source of cross-platform divergence.
    files = sorted((path for folder in ("src", "tests")
                    for path in (ROOT / folder).rglob("*.py")),
                   key=lambda q: q.relative_to(ROOT).as_posix())
    # The stored details are this script's output, so a change to it means the record no
    # longer describes what the checks would now report. state_table.py is excluded on
    # purpose: verification renders fresh and compares, so a renderer change cannot go
    # stale -- hashing it would only force a re-run to adjust a caption.
    files.append(ROOT / "validation" / "release_check.py")
    for path in files:
        rel = path.relative_to(ROOT).as_posix()
        body = path.read_bytes().replace(b"\r\n", b"\n")
        # Line endings are normalised because `.gitattributes` declares `* text=auto eol=lf`
        # while this working tree checks many files out as CRLF. Hashing raw bytes bound the
        # record to one machine's endings, so `git checkout .` or any Linux clone invalidated
        # it with no code changed. Lengths are written in so `relpath || body` cannot be
        # re-partitioned into a different file set that hashes the same.
        h.update(f"{len(rel)}:{rel}:{len(body)}:".encode())
        h.update(body)
    return h.hexdigest()


def _cell(text: str) -> str:
    """Make text safe inside a table cell. Check 5 joins its validators with " | "."""
    # Newlines too: check 7's failure detail carries a raw stderr tail, and one embedded
    # newline turns a row into body text and silently ends the table.
    flat = " ".join(text.split())
    return flat.replace("|", "\\|")


def _detail(checks: list[dict], prefix: str) -> str:
    for c in checks:
        if c["check"].startswith(prefix):
            return _cell(c["detail"])
    raise Stale(f"the record has no check numbered {prefix}")


def _load() -> list[dict]:
    if not RECORD.is_file():
        raise Stale(f"{RECORD.relative_to(ROOT)} does not exist -- run "
                    f"validation/release_check.py first")
    record = json.loads(RECORD.read_text(encoding="utf-8"))
    checks = record.get("checks")
    if not checks:
        raise Stale("the record holds no checks")

    stored = record.get("inputs_sha256")
    if stored is None:
        raise Stale("the record carries no input digest, so it cannot be bound to this tree "
                    "-- re-run validation/release_check.py to write one that does")
    current = inputs_fingerprint()
    if stored != current:
        raise Stale(f"the record was produced over src/, tests/ and release_check.py at "
                    f"{stored[:12]} and the tree computes {current[:12]} -- re-run "
                    f"validation/release_check.py")
    return checks


def _notebooks_row(checks: list[dict]) -> str:
    parts = []
    for label, name in NOTEBOOKS:
        path = ROOT / "notebooks" / name
        if not path.is_file():
            parts.append(f"{label}: **missing**")
            continue
        cells = json.loads(path.read_text(encoding="utf-8"))["cells"]
        code = sum(1 for c in cells if c["cell_type"] == "code")
        parts.append(f"{label}: **{len(cells)} cells ({code} code)**")
    execution = _detail(checks, "7.")
    return f"| notebooks | {'. '.join(parts)}. Execution: {execution} |"


def _release_row(checks: list[dict]) -> str:
    """Every check except the one that gates this row.

    Including check 11 would be circular: its result depends on whether this row matches, and
    this row would then depend on its result, so the two could never agree. The record keeps
    all twelve; the row reports the eleven whose verdicts are independent of it.
    """
    checks = [c for c in checks if not c["check"].startswith("11.")]
    passed = sum(1 for c in checks if c["ok"] is True)
    failed = [c["check"] for c in checks if c["ok"] is False]
    manual = [c["check"] for c in checks if c["ok"] is None]
    verdict = f"**{passed} of {len(checks)} passed**"
    if failed:
        verdict += f", **{len(failed)} failed** ({'; '.join(failed)})"
    if manual:
        verdict += f", **{len(manual)} needing a human** ({'; '.join(manual)})"
    if not failed and not manual:
        verdict += ", 0 failed, **0 needing a human**"
    return (f"| release check | {_cell(verdict)}. Check 11 gates this table itself and is "
            f"excluded here to keep the two from being circular — the record holds it |")


def render() -> str:
    checks = _load()
    rows = [
        BEGIN,
        "",
        "*Every row below is rendered from measured artefacts by "
        "`validation/state_table.py`; `release_check.py` check 11 fails when it stops "
        "matching. Edit the measurement, not the number.*",
        "",
        "*Nothing here carries a timestamp or a commit on purpose: the block is rewritten by "
        "every release-check run, so volatile values in it would make check 11 fail "
        "immediately after each run and a green gate unreachable. The guarantee is stronger "
        "without them — these rows only render while the record's digest over `src/`, `tests/` "
        "and `release_check.py` matches this tree. `work/release/release_check.json` holds the "
        "commit and the time.*",
        "",
        "| | |",
        "|---|---|",
        f"| tests | **{_detail(checks, '1.')}** — `pytest tests/ -q` |",
        _release_row(checks),
        f"| independent evidence | {_detail(checks, '5.')} |",
        _notebooks_row(checks),
        f"| architecture coverage | {_detail(checks, '4.')} |",
        f"| runtime | {_detail(checks, '9.')} |",
        "",
        END,
    ]
    return "\n".join(rows)


def _split(text: str) -> tuple[str, str]:
    if BEGIN not in text or END not in text:
        raise Stale(f"{HANDOVER.name} has no STATE block -- add the BEGIN and END markers "
                    f"around the generated rows once, by hand")
    before, rest = text.split(BEGIN, 1)
    _, after = rest.split(END, 1)
    return before, after


def main() -> int:
    ap = argparse.ArgumentParser(description="keep the handover's State table measured")
    ap.add_argument("--write", action="store_true",
                    help="rewrite the block instead of verifying it")
    args = ap.parse_args()

    try:
        block = render()
    except Stale as exc:
        print(f"cannot render the State table: {exc}")
        return 1

    text = HANDOVER.read_text(encoding="utf-8")
    try:
        before, after = _split(text)
    except Stale as exc:
        print(f"cannot locate the State table: {exc}")
        return 1

    wanted = before + block + after
    if args.write:
        if wanted == text:
            print("State table already matches the measured values; nothing written")
            return 0
        HANDOVER.write_text(wanted, encoding="utf-8")
        print(f"rewrote the State table in {HANDOVER.name} from measured values")
        return 0

    if wanted == text:
        print("State table matches the measured values")
        return 0
    current = text.split(BEGIN, 1)[1].split(END, 1)[0]
    expected = block.split(BEGIN, 1)[1].split(END, 1)[0]
    print(f"{HANDOVER.name} is STALE. Run: python validation/state_table.py --write\n")
    for line in expected.splitlines():
        if line.startswith("|") and line not in current:
            print(f"  measured : {line}")
    for line in current.splitlines():
        if line.startswith("|") and line not in expected:
            print(f"  recorded : {line}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
